### ISSUE TITLE
Latex seems to be not rendered

### ISSUE THREAD

**Issue by kamranmuazzam** [mixasite/obsidian-mixa#2]

**Comment by mixasite** [comment]
Hey Kamran,

Could you please share a page with latex so that we can investigate?

We've check some of the pages, and it seems to be working:
https://kay.mixa.site/Medic/Basic%20Sciences/Pharmacology/General%20Pharmacology/Pharmacodynamics/Dose-Response%20Relationship/Therapeutic%20Index

Please let us know,
Thanks
